name: Android CI

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Allow execution of gradlew
        run: chmod +x ./gradlew

      - name: Enable script execution
        run: |
          sudo chmod +x /usr/bin/pwsh

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build app
        run: ./gradlew assemble

      - name: Install Ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run Ktlint on modules
        run: ktlint --version && ./gradlew ktlintCheck

